### ISSUE TITLE
Bump Elixir version number

### ISSUE THREAD

**Issue by justgage** [ericmj/ex2ms#12]
Would it be possible to bump the version number for Elixir? Is there changes that need to be made?

**Comment by ericmj** [comment]
Are you referring to the version requirement on elixir in mix.exs? Are you having issues with it?

**Comment by justgage** [comment]
Yeah I'm getting the following error:
```
warning: the dependency :ex2ms requires Elixir "<= 1.3.0" but you are running on v1.3.2
```
It seems to work fine with the newer version so it seems to make sense to update it right?

**Comment by ericmj** [comment]
The version is correct on master. We need a new release but I no longer maintain the package on Hex.

/cc @MSch

**Comment by ianschreuder** [comment]
+1 for updating the hex release.

**Comment by dc0d** [comment]
This issue is still not resolved:

```
warning: the dependency :ex2ms requires Elixir "<= 1.3.0" but you are running on v1.3.4
```

**Comment by Douvi** [comment]
can you do a release on Hex ?

**Comment by ericmj** [comment]
I added myself as owner again and released a new version. Sorry about the delay :(.
