### ISSUE TITLE
Are match functions statically defined at compile?

### ISSUE THREAD

**Issue by Dania02525** [ericmj/ex2ms#15]
Considering something like this:
`[{{:"$1", :"$2", :"$3"}, [],[:>,:"$3",:os.system_time(:seconds)]}]`

Will this always evaluate to the system time at compile, or is there a way for it to be dynamic?

**Comment by ericmj** [comment]
`[{{:"$1", :"$2", :"$3"}, [],[:>,:"$3",:os.system_time(:seconds)]}]` is code like any other Elixir code. It will be evaluated when the code around it is evaluated.

**Comment by Dania02525** [comment]
Maybe more of a general ets match specification question, but will the above code execute `:os.system_time` each time ets checks for a match, or will it be evaluated one time, with the match comparing to the same timestamp over and over again? behavior seems to be the latter

**Comment by ericmj** [comment]
If you have

```elixir
def foo() do
  [{{:"$1", :"$2", :"$3"}, [],[:>,:"$3",:os.system_time(:seconds)]}]
end
```

it will be executed every time the function is called the same way the following code is

```elixir
def foo() do
  [:os.system_time(:seconds)]
end
```

A match expression is just an Elixir value like any other.
