### ISSUE TITLE
Error when matching against tuples

### ISSUE THREAD

**Issue by lud** [ericmj/ex2ms#24]
Hi, 

I try to match the keys against 3-tuples

This is my first attempt:

```
   key_start = {2019, 6, 10}
   key_end = {2019, 6, 12}

    match_fun =
      fun do
        {key, day} = record
        when key >= ^key_start and
               key <= ^key_end ->
          day
      end
```

And this is the result: 

```
[
  {{:"$1", :"$2"},
   [{:andalso, {:>=, :"$1", {2019, 6, 10}}, {:"=<", :"$1", {2019, 6, 12}}}],
   [:"$2"]}
]
```

It's wrong because the 3-tuples should be wrapped in 1-tuples like this:

```
[
  {{:"$1", :"$2"},
   [
     {:andalso, {:>=, :"$1", {{2019, 6, 10}}},
      {:"=<", :"$1", {{2019, 6, 12}}}}
   ], [:"$2"]}
]
```

I tried this:

```
    match_fun =
      fun do
        {key, day} = record
        when key >= {^key_start} and
               key <= {^key_end} ->
          day
      end
```

But there is now an extra level of wrapping, which is expected I guess:

```
[
  {{:"$1", :"$2"},
   [
     {:andalso, {:>=, :"$1", {{{2019, 6, 10}}}},
      {:"=<", :"$1", {{{2019, 6, 12}}}}}
   ], [:"$2"]}
]
```

Is there a way to get the expected result, or is it a bug ?

Thank you

**Comment by ericmj** [comment]
It's a bug. We need to escape all interpolated composite terms or wrap them in `{:const, ...}`.

**Comment by lud** [comment]
The basic trick would be to do that for guard clauses:

```elixir
  defp translate_cond({:^, _, [var]}, _state) do
    {{:unquote, [], [var]}}
  end
```

But it fails a `gproc` test. We must be able to know by `state` if we already are inside a constant or defining one.

**Comment by ericmj** [comment]
I don't think there would be any nested consts since we don't use `:const` at all today in ex2ms.

**Comment by lud** [comment]
You use 1-tuples according to the results I could see. I mean the unwrapping method would be the same, but using `:const` give less chances of false positives.
I'd be gald to work on this but I would not be able to guess what the better solution is.

**Comment by ericmj** [comment]
I think this would work:

```elixir
  defp translate_cond({:^, _, [var]}, _state) do
    {:const, {:unquote, [], [var]}}
  end
```

**Comment by lud** [comment]
Ok so I did a quick experiment and added a test with `ets:test_ms(Tuple, MatchSpec)` and everything seems fine.

Althoug I think testing agains a real ETS table and a gproc instance could be a good thing.
