### ISSUE TITLE
!= -> /= is missing in @elixir_erlang

### ISSUE THREAD

**Issue by takscape** [ericmj/ex2ms#6]
Elixir's operator `!=` should be translated to Erlang's `/=` operator but is missing in `@elixir_erlang`.

**Comment by zackehh** [comment]
I'm not sure this is still functioning correctly:

```elixir
iex(4)> fun do { a, b } when a != 5 -> true end                   
[{{:"$1", :"$2"}, [{:!=, :"$1", 5}], [true]}]
```

Using latest version on Hex.

**Comment by ericmj** [comment]
They latest fixes are not on hex yet. /cc @MSch

**Comment by MSch** [comment]
Pushed 1.4.0 now, sorry for taking so long.
